# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: on_push

env:
  myVar: 42

on:
  push:
    branches: [ "*" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: a script
        run: |
          echo ${{ vars.ENV1_VARIABLE }}
          echo ${{ vars.ENV1_SECRET }}
          echo "$ENV1_VARIABLE"
          echo "$ENV1_SECRET"
          echo "$REPO_SECRET"
          echo ${{ secrets.REPO_SECRET }}

      # - name: a script
      #   env:
      #     ENV_MY_VAR: ${{ env.myVar }}
      #   run: |
      #     echo "hello world"
      #     echo "$myVar"
      #     echo $myVar
      #     echo ${{ env.myVar }}
      #     echo $ENV_MY_VAR

      # - name: 'Checkout'
      #   uses: actions/checkout@v3

      # - name: 'Run Tests'
      #   run: swift test --parallel
